alter table EGBPA_NOCAPPLICATION add column state_id bigint;

alter table EGBPA_NOCAPPLICATION ADD CONSTRAINT FK_EGBPA_NOCAPPLICATION_STATES FOREIGN KEY (state_id)
      REFERENCES EG_WF_STATES (ID) ;