INSERT INTO chandigarh.eg_wf_matrix (id,department,objecttype,currentstate,currentstatus,pendingactions,currentdesignation,additionalrule,nextstate,nextaction,nextdesignation,nextstatus,validactions,fromqty,toqty,fromdate,todate,"version",enablefields,forwardenabled,smsemailenabled,nextref,rejectenabled) VALUES
	 (424,'ANY','OccupancyCertificate','NEW','','Occupancy certificate application creation pending','','Low Risk','Registered','Forwarded to verify application documents','Building Assistant Urban','Registered','Forward',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL),
	 (425,'ANY','OccupancyCertificate','Registered','Registered','Forwarded to verify application documents','','Low Risk','Application documents verification in progress','Forwarded to review application documents','Junior Engineer Urban','Document Verification Completed','Forward',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL),
	 (426,'ANY','OccupancyCertificate','Application documents verification in progress','Document Verification Completed','Forwarded to review application documents','','Low Risk','Forward to Head Draftsman','Forwarded to Head Draftsman for review','Head Draftsman Urban','Application Reviewed','Forward,Reject',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL),
	 (427,'ANY','OccupancyCertificate','Forward to Head Draftsman','Application Reviewed','Forwarded to Head Draftsman for review','','Low Risk','Forward to SDO Building','Forwarded to SDO Building for review','SDO Building Urban','Document Reviewed','Forward',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL),
	 (428,'ANY','OccupancyCertificate','Forward to SDO Building','Document Reviewed','Forwarded to SDO Building for review','','Low Risk','AEE Application Approval Pending','Forwarded to E- Assistant Estate Officer for Approval','Assistant Estate Officer','Application Reviewed','Forward,Reject',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL),
	 (429,'ANY','OccupancyCertificate','Record Approved',NULL,'Forwarded to generate Occupancy Certificate','','Low Risk','END','END','SDO Building Urban','Order Issued to Applicant','Generate Occupancy Certificate',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL),
	 (430,'ANY','OccupancyCertificate','Rejected','','','','Low Risk','generate rejection notice','Application is rejected by approver','SDO Building Urban','Rejected','Generate Rejection Notice',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL),
	 (431,'ANY','OccupancyCertificate','LP Initiated','','','','Low Risk','LP Created','Letter To Party Reply Pending','SDO Building Urban','Letter To Party Created','Forward',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL),
	 (432,'ANY','OccupancyCertificate','LP Created','','','','Low Risk','LP Reply Received','Forward to LP Initiator pending','SDO Building Urban','Letter To Party Reply Received','Forward',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL),
	 (433,'ANY','OccupancyCertificate','Final Approval Process initiated','AEE Approval Completed','Occupancy certificate fee collection pending','','Low Risk','Record Approved','Occupancy certificate fee collection pending','SDO Building Urban','Approved','Approve,Reject',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL);
INSERT INTO chandigarh.eg_wf_matrix (id,department,objecttype,currentstate,currentstatus,pendingactions,currentdesignation,additionalrule,nextstate,nextaction,nextdesignation,nextstatus,validactions,fromqty,toqty,fromdate,todate,"version",enablefields,forwardenabled,smsemailenabled,nextref,rejectenabled) VALUES
	 (434,'ANY','OccupancyCertificate','Record Approved',NULL,'Occupancy certificate fee collection pending','','Low Risk','Record Approved','Forwarded to generate Occupancy Certificate','SDO Building Urban','Approved','Generate Occupancy Certificate',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL),
	 (435,'ANY','OccupancyCertificate','AEE Application Approval Pending','NOC Updated','Forwarded to E- Assistant Estate Officer for Approval','','Low Risk','Final Approval Process initiated','Occupancy certificate fee collection pending','Estate Officer','AEE Approval Completed','Forward,Reject',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL);