SELECT setval('state.seq_eg_role',(SELECT max(id) FROM state.eg_role));

INSERT INTO state.eg_role (id,"name",description,createddate,createdby,lastmodifiedby,lastmodifieddate,"version",internal) VALUES 
(nextval('state.seq_eg_role'),'BPA_ROAD_2_NOC_RURAL_ROLE','Role for users who approve/provides a NOC from Road 2 department for Rural',now(),1,1,now(),0,false)
,(nextval('state.seq_eg_role'),'BPA_PAC_NOC_RURAL_ROLE','Role for users who approve/provides a NOC from Urban Planning Department (PAC) department for Rural',now(),1,1,now(),0,false)
,(nextval('state.seq_eg_role'),'BPA_STRUCTURE_NOC_RURAL_ROLE','Role for users who approve/provides a NOC from Structure department for Rural',now(),1,1,now(),0,false)
,(nextval('state.seq_eg_role'),'BPA_ELECTRICAL_NOC_RURAL_ROLE','Role for users who approve/provides a NOC from Electrical department for Rural',now(),1,1,now(),0,false)
,(nextval('state.seq_eg_role'),'BPA_POL_CONTROL_NOC_RURAL_ROLE','Role for users who approve/provides a NOC from Pollution control department for Rural',now(),1,1,now(),0,false)
,(nextval('state.seq_eg_role'),'BPA_MANIMAJARA_NOC_RURAL_ROLE','Role for users who approve/provides a NOC from Sub-Office Manimajara department for Rural',now(),1,1,now(),0,false)
,(nextval('state.seq_eg_role'),'BPA_FIRE_NOC_RURAL_ROLE','Role for users who approve/provides a NOC from Fire department for Rural',now(),1,1,now(),0,false)
,(nextval('state.seq_eg_role'),'BPA_PUB_HEALTH_7_NOC_RURAL_ROLE','Role for users who approve/provides a NOC from Public health 7 Department for Rural',now(),1,1,now(),0,false)
,(nextval('state.seq_eg_role'),'BPA_TEHSILDAR_NOC_RURAL_ROLE','Role for users who approve/provides a NOC from Tehsildar department for Rural',now(),1,1,now(),0,false)
,(nextval('state.seq_eg_role'),'BPA_PUB_HEALTH_NOC_RURAL_ROLE','Role for users who approve/provides a NOC from Public health department for Rural',now(),1,1,now(),0,false)
,(nextval('state.seq_eg_role'),'BPA_AC_TAX_NOC_RURAL_ROLE','Role for users who approve/provides a NOC from AC Tax department for Rural',now(),1,1,now(),0,false);


INSERT INTO state.eg_user select nextval('state.seq_eg_user'), 'state', NULL, NULL, NULL, 'en_IN', 'road2nocrural', '$2a$10$Yo7HoeymnnjmAR.kPU51Lu5OMd5bvYR52MtLoN9NLIjwJaG8RIdrS', '2025-12-31 00:00:00.000', 3331234567, NULL, NULL,  now(), now(), 1, 1, true, 'Road 2 Department Rural', NULL, NULL, NULL, 'BUSINESS', 0, NULL, NULL, 'state' where not exists (select * from state.eg_user where username='road2nocrural');
INSERT INTO state.eg_user select nextval('state.seq_eg_user'), 'state', NULL, NULL, NULL, 'en_IN', 'pacnocrural', '$2a$10$Yo7HoeymnnjmAR.kPU51Lu5OMd5bvYR52MtLoN9NLIjwJaG8RIdrS', '2025-12-31 00:00:00.000', 3331234568, NULL, NULL,  now(), now(), 1, 1, true, 'Urban Planning Department Rural', NULL, NULL, NULL, 'BUSINESS', 0, NULL, NULL, 'state' where not exists (select * from state.eg_user where username='pacnocrural');
INSERT INTO state.eg_user select nextval('state.seq_eg_user'), 'state', NULL, NULL, NULL, 'en_IN', 'structurenocrural', '$2a$10$Yo7HoeymnnjmAR.kPU51Lu5OMd5bvYR52MtLoN9NLIjwJaG8RIdrS', '2025-12-31 00:00:00.000', 3331234569, NULL, NULL,  now(), now(), 1, 1, true, 'Structure Department Rural', NULL, NULL, NULL, 'BUSINESS', 0, NULL, NULL, 'state' where not exists (select * from state.eg_user where username='structurenocrural');
INSERT INTO state.eg_user select nextval('state.seq_eg_user'), 'state', NULL, NULL, NULL, 'en_IN', 'electricalnocrural', '$2a$10$Yo7HoeymnnjmAR.kPU51Lu5OMd5bvYR52MtLoN9NLIjwJaG8RIdrS', '2025-12-31 00:00:00.000', 3331234570, NULL, NULL,  now(), now(), 1, 1, true, 'Electrical Department Rural', NULL, NULL, NULL, 'BUSINESS', 0, NULL, NULL, 'state' where not exists (select * from state.eg_user where username='electricalnocrural');
INSERT INTO state.eg_user select nextval('state.seq_eg_user'), 'state', NULL, NULL, NULL, 'en_IN', 'polcontrolnocrural', '$2a$10$Yo7HoeymnnjmAR.kPU51Lu5OMd5bvYR52MtLoN9NLIjwJaG8RIdrS', '2025-12-31 00:00:00.000', 3331234571, NULL, NULL,  now(), now(), 1, 1, true, 'Pollution Control Department Rural', NULL, NULL, NULL, 'BUSINESS', 0, NULL, NULL, 'state' where not exists (select * from state.eg_user where username='polcontrolnocrural');
INSERT INTO state.eg_user select nextval('state.seq_eg_user'), 'state', NULL, NULL, NULL, 'en_IN', 'manimajaranocrural', '$2a$10$Yo7HoeymnnjmAR.kPU51Lu5OMd5bvYR52MtLoN9NLIjwJaG8RIdrS', '2025-12-31 00:00:00.000', 3331234572, NULL, NULL,  now(), now(), 1, 1, true, 'Sub-Office Manimajara Department Rural', NULL, NULL, NULL, 'BUSINESS', 0, NULL, NULL, 'state' where not exists (select * from state.eg_user where username='manimajaranocrural');
INSERT INTO state.eg_user select nextval('state.seq_eg_user'), 'state', NULL, NULL, NULL, 'en_IN', 'firenocrural', '$2a$10$Yo7HoeymnnjmAR.kPU51Lu5OMd5bvYR52MtLoN9NLIjwJaG8RIdrS', '2025-12-31 00:00:00.000', NULL, 3331234573, NULL,  now(), now(), 1, 1, true, 'Fire NOC Department Rural', NULL, NULL, NULL, 'BUSINESS', 0, NULL, NULL, 'state' where not exists (select * from state.eg_user where username='firenocrural');
INSERT INTO state.eg_user select nextval('state.seq_eg_user'), 'state', NULL, NULL, NULL, 'en_IN', 'pubhealth7nocrural', '$2a$10$Yo7HoeymnnjmAR.kPU51Lu5OMd5bvYR52MtLoN9NLIjwJaG8RIdrS', '2025-12-31 00:00:00.000', 3331234574, NULL, NULL,  now(), now(), 1, 1, true, 'Public Health Seven NOC Rural', NULL, NULL, NULL, 'BUSINESS', 0, NULL, NULL, 'state' where not exists (select * from state.eg_user where username='pubhealth7nocrural');
INSERT INTO state.eg_user select nextval('state.seq_eg_user'), 'state', NULL, NULL, NULL, 'en_IN', 'tehsildarnocrural', '$2a$10$Yo7HoeymnnjmAR.kPU51Lu5OMd5bvYR52MtLoN9NLIjwJaG8RIdrS', '2025-12-31 00:00:00.000', 3331234575, NULL, NULL,  now(), now(), 1, 1, true, 'Tehsildar NOC Rural', NULL, NULL, NULL, 'BUSINESS', 0, NULL, NULL, 'state' where not exists (select * from state.eg_user where username='tehsildarnocrural');
INSERT INTO state.eg_user select nextval('state.seq_eg_user'), 'state', NULL, NULL, NULL, 'en_IN', 'pubhealthnocrural', '$2a$10$Yo7HoeymnnjmAR.kPU51Lu5OMd5bvYR52MtLoN9NLIjwJaG8RIdrS', '2025-12-31 00:00:00.000', 3331234576, NULL, NULL,  now(), now(), 1, 1, true, 'Public Health NOC Rural', NULL, NULL, NULL, 'BUSINESS', 0, NULL, NULL, 'state' where not exists (select * from state.eg_user where username='pubhealthnocrural');
INSERT INTO state.eg_user select nextval('state.seq_eg_user'), 'state', NULL, NULL, NULL, 'en_IN', 'actaxnocrural', '$2a$10$Yo7HoeymnnjmAR.kPU51Lu5OMd5bvYR52MtLoN9NLIjwJaG8RIdrS', '2025-12-31 00:00:00.000', 3331234577, NULL, NULL, now(), now(), 1, 1, true, 'AC Tax department Rural', NULL, NULL, NULL, 'BUSINESS', 0, NULL, NULL, 'state' where not exists (select * from state.eg_user where username='actaxnocrural');


INSERT into state.eg_userrole select (select id from state.eg_role where name = 'BPA_ROAD_2_NOC_RURAL_ROLE'), (select id from state.eg_user where username ='road2nocrural') where not exists (SELECT * FROM state.eg_userrole WHERE roleid in (select id from state.eg_role where name = 'BPA_ROAD_2_NOC_RURAL_ROLE'));
INSERT into state.eg_userrole select (select id from state.eg_role where name = 'BPA_PAC_NOC_RURAL_ROLE'), (select id from state.eg_user where username ='pacnocrural') where not exists (SELECT * FROM state.eg_userrole WHERE roleid in (select id from state.eg_role where name = 'BPA_PAC_NOC_RURAL_ROLE'));
INSERT into state.eg_userrole select (select id from state.eg_role where name = 'BPA_STRUCTURE_NOC_RURAL_ROLE'), (select id from state.eg_user where username ='structurenocrural') where not exists (SELECT * FROM state.eg_userrole WHERE roleid in (select id from state.eg_role where name = 'BPA_STRUCTURE_NOC_RURAL_ROLE'));
INSERT into state.eg_userrole select (select id from state.eg_role where name = 'BPA_ELECTRICAL_NOC_RURAL_ROLE'), (select id from state.eg_user where username ='electricalnocrural') where not exists (SELECT * FROM state.eg_userrole WHERE roleid in (select id from state.eg_role where name = 'BPA_ELECTRICAL_NOC_RURAL_ROLE'));
INSERT into state.eg_userrole select (select id from state.eg_role where name = 'BPA_POL_CONTROL_NOC_RURAL_ROLE'), (select id from state.eg_user where username ='polcontrolnocrural') where not exists (SELECT * FROM state.eg_userrole WHERE roleid in (select id from state.eg_role where name = 'BPA_POL_CONTROL_NOC_RURAL_ROLE'));
INSERT into state.eg_userrole select (select id from state.eg_role where name = 'BPA_MANIMAJARA_NOC_RURAL_ROLE'), (select id from state.eg_user where username ='manimajaranocrural') where not exists (SELECT * FROM state.eg_userrole WHERE roleid in (select id from state.eg_role where name = 'BPA_MANIMAJARA_NOC_RURAL_ROLE'));
INSERT into state.eg_userrole select (select id from state.eg_role where name = 'BPA_FIRE_NOC_RURAL_ROLE'), (select id from state.eg_user where username ='firenocrural') where not exists (SELECT * FROM state.eg_userrole WHERE roleid in (select id from state.eg_role where name = 'BPA_FIRE_NOC_RURAL_ROLE'));
INSERT into state.eg_userrole select (select id from state.eg_role where name = 'BPA_PUB_HEALTH_7_NOC_RURAL_ROLE'), (select id from state.eg_user where username ='pubhealth7nocrural') where not exists (SELECT * FROM state.eg_userrole WHERE roleid in (select id from state.eg_role where name = 'BPA_PUB_HEALTH_7_NOC_RURAL_ROLE'));
INSERT into state.eg_userrole select (select id from state.eg_role where name = 'BPA_TEHSILDAR_NOC_RURAL_ROLE'), (select id from state.eg_user where username ='tehsildarnocrural') where not exists (SELECT * FROM state.eg_userrole WHERE roleid in (select id from state.eg_role where name = 'BPA_TEHSILDAR_NOC_RURAL_ROLE'));
INSERT into state.eg_userrole select (select id from state.eg_role where name = 'BPA_PUB_HEALTH_NOC_RURAL_ROLE'), (select id from state.eg_user where username ='pubhealthnocrural') where not exists (SELECT * FROM state.eg_userrole WHERE roleid in (select id from state.eg_role where name = 'BPA_PUB_HEALTH_NOC_RURAL_ROLE'));
INSERT into state.eg_userrole select (select id from state.eg_role where name = 'BPA_AC_TAX_NOC_RURAL_ROLE'), (select id from state.eg_user where username ='actaxnocrural') where not exists (SELECT * FROM state.eg_userrole WHERE roleid in (select id from state.eg_role where name = 'BPA_AC_TAX_NOC_RURAL_ROLE'));


INSERT into state.eg_userrole select (select id from state.eg_role where name = 'BUSINESS'), (select id from state.eg_user where username ='road2nocrural');
INSERT into state.eg_userrole select (select id from state.eg_role where name = 'BUSINESS'), (select id from state.eg_user where username ='pacnocrural');
INSERT into state.eg_userrole select (select id from state.eg_role where name = 'BUSINESS'), (select id from state.eg_user where username ='structurenocrural');
INSERT into state.eg_userrole select (select id from state.eg_role where name = 'BUSINESS'), (select id from state.eg_user where username ='electricalnocrural');
INSERT into state.eg_userrole select (select id from state.eg_role where name = 'BUSINESS'), (select id from state.eg_user where username ='polcontrolnocrural');
INSERT into state.eg_userrole select (select id from state.eg_role where name = 'BUSINESS'), (select id from state.eg_user where username ='manimajaranocrural');
INSERT into state.eg_userrole select (select id from state.eg_role where name = 'BUSINESS'), (select id from state.eg_user where username ='firenocrural');
INSERT into state.eg_userrole select (select id from state.eg_role where name = 'BUSINESS'), (select id from state.eg_user where username ='pubhealth7nocrural');
INSERT into state.eg_userrole select (select id from state.eg_role where name = 'BUSINESS'), (select id from state.eg_user where username ='tehsildarnocrural');
INSERT into state.eg_userrole select (select id from state.eg_role where name = 'BUSINESS'), (select id from state.eg_user where username ='pubhealthnocrural');
INSERT into state.eg_userrole select (select id from state.eg_role where name = 'BUSINESS'), (select id from state.eg_user where username ='actaxnocrural');
