INSERT INTO chandigarh.eg_checklist (id,checklisttypeid,code,description,"version",createdby,createddate,lastmodifiedby,lastmodifieddate) VALUES 
(nextval('seq_eg_checklist'),(select id from chandigarh.eg_checklist_type where code='DOCUMENTATION'),'DOCUMENTATION-22','Checklist duly filled & signed by the Private Architect.',0,1,now(),1,now())
,(nextval('seq_eg_checklist'),(select id from chandigarh.eg_checklist_type where code='DOCUMENTATION'),'DOCUMENTATION-23','In case of allotment of society, NOC from the Chandigarh Housing Board or Society Registrar required.',0,1,now(),1,now())
,(nextval('seq_eg_checklist'),(select id from chandigarh.eg_checklist_type where code='DOCUMENTATION'),'DOCUMENTATION-24','Structure design requirements: (a) Certification stating structural safety of existing, adjoining structures shall be ensured during dismantling and execution etc. (b) Certification stating structural design is as per prevailing IS Codal provision for safety, designing and execution.',0,1,now(),1,now())
,(nextval('seq_eg_checklist'),(select id from chandigarh.eg_checklist_type where code='DOCUMENTATION'),'DOCUMENTATION-25','Structure design requirements: (a) Staad file for building structure verification',0,1,now(),1,now())
,(nextval('seq_eg_checklist'),(select id from chandigarh.eg_checklist_type where code='DOCUMENTATION'),'DOCUMENTATION-26','Documents to be attached in case of plot amalgamation',0,1,now(),1,now())
,(nextval('seq_eg_checklist'),(select id from chandigarh.eg_checklist_type where code='DOCUMENTATION'),'DOCUMENTATION-27','Agreement from the owner and competent authority from Estate office if projections are in government land',0,1,now(),1,now())
,(nextval('seq_eg_checklist'),(select id from chandigarh.eg_checklist_type where code='DOCUMENTATION'),'DOCUMENTATION-28','Affidavit',0,1,now(),1,now())
,(nextval('seq_eg_checklist'),(select id from chandigarh.eg_checklist_type where code='DOCUMENTATION'),'DOCUMENTATION-29','Sale deed / Mutation / Jamabandi / Fard attested by notary',0,1,now(),1,now())
,(nextval('seq_eg_checklist'),(select id from chandigarh.eg_checklist_type where code='DOCUMENTATION'),'DOCUMENTATION-30','Revenue Patwaris report duly counter signed by Tehsildar',0,1,now(),1,now())
,(nextval('seq_eg_checklist'),(select id from chandigarh.eg_checklist_type where code='DOCUMENTATION'),'DOCUMENTATION-31','Copy of latest electricity bill, if any',0,1,now(),1,now())
,(nextval('seq_eg_checklist'),(select id from chandigarh.eg_checklist_type where code='DOCUMENTATION'),'DOCUMENTATION-32','Specimen signatures along with photograph of the owner/ applicant duly signed and attested by a gazetted officer or Executive Magistrate',0,1,now(),1,now())
,(nextval('seq_eg_checklist'),(select id from chandigarh.eg_checklist_type where code='DOCUMENTATION'),'DOCUMENTATION-33','Indemnity bond',0,1,now(),1,now())
,(nextval('seq_eg_checklist'),(select id from chandigarh.eg_checklist_type where code='DOCUMENTATION'),'DOCUMENTATION-34','Plan. (Application in case of property owned by the Company).',0,1,now(),1,now())
;

INSERT INTO chandigarh.egbpa_checklist_servicetype_mapping (id,checklist,servicetype,isrequired,ismandatory,"version",createdby,createddate,lastmodifiedby,lastmodifieddate) VALUES 
(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-22'),(select id from chandigarh.egbpa_mstr_servicetype where code='01'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-23'),(select id from chandigarh.egbpa_mstr_servicetype where code='01'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-24'),(select id from chandigarh.egbpa_mstr_servicetype where code='01'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-25'),(select id from chandigarh.egbpa_mstr_servicetype where code='01'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-26'),(select id from chandigarh.egbpa_mstr_servicetype where code='01'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-27'),(select id from chandigarh.egbpa_mstr_servicetype where code='01'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-28'),(select id from chandigarh.egbpa_mstr_servicetype where code='01'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-29'),(select id from chandigarh.egbpa_mstr_servicetype where code='01'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-30'),(select id from chandigarh.egbpa_mstr_servicetype where code='01'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-31'),(select id from chandigarh.egbpa_mstr_servicetype where code='01'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-32'),(select id from chandigarh.egbpa_mstr_servicetype where code='01'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-33'),(select id from chandigarh.egbpa_mstr_servicetype where code='01'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-34'),(select id from chandigarh.egbpa_mstr_servicetype where code='01'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-22'),(select id from chandigarh.egbpa_mstr_servicetype where code='03'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-23'),(select id from chandigarh.egbpa_mstr_servicetype where code='03'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-24'),(select id from chandigarh.egbpa_mstr_servicetype where code='03'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-25'),(select id from chandigarh.egbpa_mstr_servicetype where code='03'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-26'),(select id from chandigarh.egbpa_mstr_servicetype where code='03'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-27'),(select id from chandigarh.egbpa_mstr_servicetype where code='03'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-28'),(select id from chandigarh.egbpa_mstr_servicetype where code='03'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-29'),(select id from chandigarh.egbpa_mstr_servicetype where code='03'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-30'),(select id from chandigarh.egbpa_mstr_servicetype where code='03'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-31'),(select id from chandigarh.egbpa_mstr_servicetype where code='03'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-32'),(select id from chandigarh.egbpa_mstr_servicetype where code='03'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-33'),(select id from chandigarh.egbpa_mstr_servicetype where code='03'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-34'),(select id from chandigarh.egbpa_mstr_servicetype where code='03'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-22'),(select id from chandigarh.egbpa_mstr_servicetype where code='04'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-23'),(select id from chandigarh.egbpa_mstr_servicetype where code='04'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-24'),(select id from chandigarh.egbpa_mstr_servicetype where code='04'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-25'),(select id from chandigarh.egbpa_mstr_servicetype where code='04'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-26'),(select id from chandigarh.egbpa_mstr_servicetype where code='04'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-27'),(select id from chandigarh.egbpa_mstr_servicetype where code='04'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-28'),(select id from chandigarh.egbpa_mstr_servicetype where code='04'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-29'),(select id from chandigarh.egbpa_mstr_servicetype where code='04'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-30'),(select id from chandigarh.egbpa_mstr_servicetype where code='04'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-31'),(select id from chandigarh.egbpa_mstr_servicetype where code='04'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-32'),(select id from chandigarh.egbpa_mstr_servicetype where code='04'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-33'),(select id from chandigarh.egbpa_mstr_servicetype where code='04'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-34'),(select id from chandigarh.egbpa_mstr_servicetype where code='04'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-22'),(select id from chandigarh.egbpa_mstr_servicetype where code='06'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-23'),(select id from chandigarh.egbpa_mstr_servicetype where code='06'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-24'),(select id from chandigarh.egbpa_mstr_servicetype where code='06'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-25'),(select id from chandigarh.egbpa_mstr_servicetype where code='06'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-26'),(select id from chandigarh.egbpa_mstr_servicetype where code='06'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-27'),(select id from chandigarh.egbpa_mstr_servicetype where code='06'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-28'),(select id from chandigarh.egbpa_mstr_servicetype where code='06'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-29'),(select id from chandigarh.egbpa_mstr_servicetype where code='06'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-30'),(select id from chandigarh.egbpa_mstr_servicetype where code='06'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-31'),(select id from chandigarh.egbpa_mstr_servicetype where code='06'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-32'),(select id from chandigarh.egbpa_mstr_servicetype where code='06'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-33'),(select id from chandigarh.egbpa_mstr_servicetype where code='06'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='DOCUMENTATION') and code='DOCUMENTATION-34'),(select id from chandigarh.egbpa_mstr_servicetype where code='06'),true,false,0,1,now(),1,now())
;

update chandigarh.eg_checklist set description = 'Form-A' where code = 'DOCUMENTATION-01' and checklisttypeid = (select id from eg_checklist_type where code = 'DOCUMENTATION');
update chandigarh.eg_checklist set description = 'Form-C' where code = 'DOCUMENTATION-02' and checklisttypeid = (select id from eg_checklist_type where code = 'DOCUMENTATION');
update chandigarh.eg_checklist set description = 'Form-J' where code = 'DOCUMENTATION-03' and checklisttypeid = (select id from eg_checklist_type where code = 'DOCUMENTATION');
update chandigarh.eg_checklist set description = 'Form-K' where code = 'DOCUMENTATION-04' and checklisttypeid = (select id from eg_checklist_type where code = 'DOCUMENTATION');
update chandigarh.eg_checklist set description = 'Form-J' where code = 'DOCUMENTATION-05' and checklisttypeid = (select id from eg_checklist_type where code = 'DOCUMENTATION');

update chandigarh.egbpa_checklist_servicetype_mapping set isrequired = true, ismandatory = false 
where checklist in (select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code = 'DOCUMENTATION'));

update chandigarh.egbpa_checklist_servicetype_mapping set isrequired = true, ismandatory = true 
where checklist in (select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code = 'DOCUMENTATION')
and code in ('DOCUMENTATION-01','DOCUMENTATION-02','DOCUMENTATION-03','DOCUMENTATION-04','DOCUMENTATION-05','DOCUMENTATION-06','DOCUMENTATION-07','DOCUMENTATION-08','DOCUMENTATION-09','DOCUMENTATION-10','DOCUMENTATION-11','DOCUMENTATION-12','DOCUMENTATION-13','DOCUMENTATION-14','DOCUMENTATION-15','DOCUMENTATION-16','DOCUMENTATION-17','DOCUMENTATION-18','DOCUMENTATION-19','DOCUMENTATION-21','DOCUMENTATION-22','DOCUMENTATION-24','DOCUMENTATION-25','DOCUMENTATION-34'));

update chandigarh.eg_checklist set description='Form-A' where code='OCGENERALDOC-01' and checklisttypeid=(select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS');
update chandigarh.eg_checklist set description='Form-E' where code='OCGENERALDOC-02' and checklisttypeid=(select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS');
update chandigarh.eg_checklist set description='Form-I' where code='OCGENERALDOC-03' and checklisttypeid=(select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS');
update chandigarh.eg_checklist set description='Form-K' where code='OCGENERALDOC-04' and checklisttypeid=(select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS');
update chandigarh.eg_checklist set description='Proof of ownership i.e. copy of allotment letter / transfer letter not more than 3 months old.' where code='OCGENERALDOC-05' and checklisttypeid=(select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS');
update chandigarh.eg_checklist set description='No dues certificate with regard to payment of entire/full amount of premium of plot (including up to date annual Ground Rent / Lease Money (Self Attested)' where code='OCGENERALDOC-06' and checklisttypeid=(select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS');
update chandigarh.eg_checklist set description='Self attested undertaking:- a)	Regarding ownership from owner(s) / applicant(s) with specimen signature, latest photographs and ID proof. b)	That there is no dispute / litigation is pending in any court of law and the properties free from all sorts of encumbrance and there is no stay / restraining order from any court of law with regard to grant of occupation certificate.' where code='OCGENERALDOC-07' and checklisttypeid=(select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS');
update chandigarh.eg_checklist set description='Copy of Sewerage Connection / Occupation Certificate or extension in time limit for construction of the building.' where code='OCGENERALDOC-08' and checklisttypeid=(select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS');
update chandigarh.eg_checklist set description='In case, sewerage connection/occupation certificate is not issued/obtained then furnish:- a)	An attested copy of proof of construction i.e., water/electricity bills (prior to 22-1-1993 or construction of building within the stipulated period as per terms and conditions of allotment or within the extended period as the case may be), supported with a certificate issued by the Registered Architect on his/her letter head certifying that the building is constructed as per sanctioned plan and there is no building violations at Site/House. b)	Certificate from the concerned water/electricity department certifying there in the date and year of release of permanent / regular water/electricity connection against the house/building in question.' where code='OCGENERALDOC-09' and checklisttypeid=(select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS');
update chandigarh.eg_checklist set description='If applicant is GPA / SPA holder, then furnish:- a)	Copy of GPA / SPA (attested by notary public). b)	Affidavit regarding validity of GPA / SPA' where code='OCGENERALDOC-10' and checklisttypeid=(select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS');
update chandigarh.eg_checklist set description='Attested Copy of partnership deed, authorization letter in favour of the authorized signatory/ partner to apply for occupation certificate. (Applicable in case of property owned by Partnership Firm).' where code='OCGENERALDOC-11' and checklisttypeid=(select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS');
update chandigarh.eg_checklist set description='Attested copy of Memorandum of Articles and Association, copy of resolution in favour of authorized signatory/ Director of the Company to apply for occupation certificate. (Application in case of property owned by the Company).' where code='OCGENERALDOC-12' and checklisttypeid=(select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS');
update chandigarh.eg_checklist set description='Photographs of elevation of front, rear and side elevation and internal showing that building is complete in all respect.' where code='OCGENERALDOC-13' and checklisttypeid=(select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS');
update chandigarh.eg_checklist set description='CD / DVD are required where showing photographs of elevation of front, rear and side elevation.' where code='OCGENERALDOC-14' and checklisttypeid=(select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS');
update chandigarh.eg_checklist set description='Certificate from Architect for Rain water harvesting system as per building bye-laws.' where code='OCGENERALDOC-15' and checklisttypeid=(select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS');
update chandigarh.eg_checklist set description='Certificate from company with regard to installation of Solar Water heating system as per building bye-laws.' where code='OCGENERALDOC-16' and checklisttypeid=(select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS');
update chandigarh.eg_checklist set description='Certificate from company with regard to installation of Solar Photo-voltaic power plant as per building bye-laws.' where code='OCGENERALDOC-17' and checklisttypeid=(select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS');
update chandigarh.eg_checklist set description='NOC is required from CFO (Chief Fire Officer) as per Fire Department, Municipal Corporation, UT, Chandigarh.' where code='OCGENERALDOC-18' and checklisttypeid=(select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS');
update chandigarh.eg_checklist set description='NOC is required from Pollution Control Board as per Fire Department, Municipal Corporation, UT, Chandigarh.' where code='OCGENERALDOC-19' and checklisttypeid=(select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS');
update chandigarh.eg_checklist set description='Copy of permission of amalgamation obtained from competent authority is required for amalgamated properties.' where code='OCGENERALDOC-20' and checklisttypeid=(select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS');


INSERT INTO chandigarh.eg_checklist (id,checklisttypeid,code,description,"version",createdby,createddate,lastmodifiedby,lastmodifieddate) VALUES 
(nextval('seq_eg_checklist'),(select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS'),'OCGENERALDOC-21','Agreement Deed is required for projections made on Govt. Land as per building bye-laws, if not submitted during Revised Building Plan. ',0,1,now(),1,now())
,(nextval('seq_eg_checklist'),(select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS'),'OCGENERALDOC-22','An undertaking from the Architect that there is no non-sanctionable & zoning violation(s) exist at site & the building violation and the sanctionable violation(s) have duly been marked on the completion plan.',0,1,now(),1,now())
,(nextval('seq_eg_checklist'),(select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS'),'OCGENERALDOC-23','Completion drawing duly signed by the architect & owner (s) and duly laminated.',0,1,now(),1,now())
,(nextval('seq_eg_checklist'),(select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS'),'OCGENERALDOC-24','Structural drawing duly signed by the owner (s), also stamped and signed by structural engineer and duly laminated.',0,1,now(),1,now());

INSERT INTO chandigarh.egbpa_checklist_servicetype_mapping (id,checklist,servicetype,isrequired,ismandatory,"version",createdby,createddate,lastmodifiedby,lastmodifieddate) VALUES 
(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS') and code='OCGENERALDOC-21'),(select id from chandigarh.egbpa_mstr_servicetype where code='01'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS') and code='OCGENERALDOC-22'),(select id from chandigarh.egbpa_mstr_servicetype where code='01'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS') and code='OCGENERALDOC-23'),(select id from chandigarh.egbpa_mstr_servicetype where code='01'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS') and code='OCGENERALDOC-24'),(select id from chandigarh.egbpa_mstr_servicetype where code='01'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS') and code='OCGENERALDOC-21'),(select id from chandigarh.egbpa_mstr_servicetype where code='03'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS') and code='OCGENERALDOC-22'),(select id from chandigarh.egbpa_mstr_servicetype where code='03'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS') and code='OCGENERALDOC-23'),(select id from chandigarh.egbpa_mstr_servicetype where code='03'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS') and code='OCGENERALDOC-24'),(select id from chandigarh.egbpa_mstr_servicetype where code='03'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS') and code='OCGENERALDOC-21'),(select id from chandigarh.egbpa_mstr_servicetype where code='04'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS') and code='OCGENERALDOC-22'),(select id from chandigarh.egbpa_mstr_servicetype where code='04'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS') and code='OCGENERALDOC-23'),(select id from chandigarh.egbpa_mstr_servicetype where code='04'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS') and code='OCGENERALDOC-24'),(select id from chandigarh.egbpa_mstr_servicetype where code='04'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS') and code='OCGENERALDOC-21'),(select id from chandigarh.egbpa_mstr_servicetype where code='06'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS') and code='OCGENERALDOC-22'),(select id from chandigarh.egbpa_mstr_servicetype where code='06'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS') and code='OCGENERALDOC-23'),(select id from chandigarh.egbpa_mstr_servicetype where code='06'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS') and code='OCGENERALDOC-24'),(select id from chandigarh.egbpa_mstr_servicetype where code='06'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS') and code='OCGENERALDOC-21'),(select id from chandigarh.egbpa_mstr_servicetype where code='07'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS') and code='OCGENERALDOC-22'),(select id from chandigarh.egbpa_mstr_servicetype where code='07'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS') and code='OCGENERALDOC-23'),(select id from chandigarh.egbpa_mstr_servicetype where code='07'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCGENERALDOCUMENTS') and code='OCGENERALDOC-24'),(select id from chandigarh.egbpa_mstr_servicetype where code='07'),true,false,0,1,now(),1,now())
;

update chandigarh.egbpa_checklist_servicetype_mapping set isrequired = true, ismandatory = true 
where checklist in (select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code = 'OCGENERALDOCUMENTS'));


update chandigarh.eg_checklist set description='Plans' where code='OCDCRDOC-01' and checklisttypeid=(select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS');
update chandigarh.eg_checklist set description='Roof Plan' where code='OCDCRDOC-02' and checklisttypeid=(select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS');
update chandigarh.eg_checklist set description='Parking plan' where code='OCDCRDOC-03' and checklisttypeid=(select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS');
update chandigarh.eg_checklist set description='Sections' where code='OCDCRDOC-04' and checklisttypeid=(select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS');

INSERT INTO chandigarh.eg_checklist (id,checklisttypeid,code,description,"version",createdby,createddate,lastmodifiedby,lastmodifieddate) VALUES 
(nextval('seq_eg_checklist'),(select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS'),'OCDCRDOC-05','Drainage plans',0,1,now(),1,now())
,(nextval('seq_eg_checklist'),(select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS'),'OCDCRDOC-06','Engineering drawings (structural)',0,1,now(),1,now())
,(nextval('seq_eg_checklist'),(select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS'),'OCDCRDOC-07','A site plan showing the position of Plot proposed to be built upon',0,1,now(),1,now())
,(nextval('seq_eg_checklist'),(select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS'),'OCDCRDOC-08','Details',0,1,now(),1,now())
,(nextval('seq_eg_checklist'),(select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS'),'OCDCRDOC-09','Other Details',0,1,now(),1,now())
,(nextval('seq_eg_checklist'),(select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS'),'OCDCRDOC-10','Elevations',0,1,now(),1,now())
;

INSERT INTO chandigarh.egbpa_checklist_servicetype_mapping (id,checklist,servicetype,isrequired,ismandatory,"version",createdby,createddate,lastmodifiedby,lastmodifieddate) VALUES 
(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-05'),(select id from chandigarh.egbpa_mstr_servicetype where code='01'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-06'),(select id from chandigarh.egbpa_mstr_servicetype where code='01'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-07'),(select id from chandigarh.egbpa_mstr_servicetype where code='01'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-08'),(select id from chandigarh.egbpa_mstr_servicetype where code='01'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-09'),(select id from chandigarh.egbpa_mstr_servicetype where code='01'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-10'),(select id from chandigarh.egbpa_mstr_servicetype where code='01'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-05'),(select id from chandigarh.egbpa_mstr_servicetype where code='03'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-06'),(select id from chandigarh.egbpa_mstr_servicetype where code='03'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-07'),(select id from chandigarh.egbpa_mstr_servicetype where code='03'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-08'),(select id from chandigarh.egbpa_mstr_servicetype where code='03'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-09'),(select id from chandigarh.egbpa_mstr_servicetype where code='03'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-10'),(select id from chandigarh.egbpa_mstr_servicetype where code='03'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-05'),(select id from chandigarh.egbpa_mstr_servicetype where code='04'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-06'),(select id from chandigarh.egbpa_mstr_servicetype where code='04'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-07'),(select id from chandigarh.egbpa_mstr_servicetype where code='04'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-08'),(select id from chandigarh.egbpa_mstr_servicetype where code='04'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-09'),(select id from chandigarh.egbpa_mstr_servicetype where code='04'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-10'),(select id from chandigarh.egbpa_mstr_servicetype where code='04'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-05'),(select id from chandigarh.egbpa_mstr_servicetype where code='06'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-06'),(select id from chandigarh.egbpa_mstr_servicetype where code='06'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-07'),(select id from chandigarh.egbpa_mstr_servicetype where code='06'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-08'),(select id from chandigarh.egbpa_mstr_servicetype where code='06'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-09'),(select id from chandigarh.egbpa_mstr_servicetype where code='06'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-10'),(select id from chandigarh.egbpa_mstr_servicetype where code='06'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-05'),(select id from chandigarh.egbpa_mstr_servicetype where code='07'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-06'),(select id from chandigarh.egbpa_mstr_servicetype where code='07'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-07'),(select id from chandigarh.egbpa_mstr_servicetype where code='07'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-08'),(select id from chandigarh.egbpa_mstr_servicetype where code='07'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-09'),(select id from chandigarh.egbpa_mstr_servicetype where code='07'),true,false,0,1,now(),1,now())
,(nextval('seq_egbpa_checklist_servicetype_mapping'),(select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code='OCDCRDOCUMENTS') and code='OCDCRDOC-10'),(select id from chandigarh.egbpa_mstr_servicetype where code='07'),true,false,0,1,now(),1,now())
;

update chandigarh.egbpa_checklist_servicetype_mapping set isrequired = true, ismandatory = true 
where checklist in (select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code = 'OCDCRDOCUMENTS'));

update chandigarh.egbpa_checklist_servicetype_mapping set isrequired = true, ismandatory = false 
where checklist in (select id from chandigarh.eg_checklist where checklisttypeid = (select id from chandigarh.eg_checklist_type where code = 'OCDCRDOCUMENTS') and code in ('OCDCRDOC-02','OCDCRDOC-03','OCDCRDOC-09'));

-- OC Fee Related Data ------------------------------------------------------------------------------------------------------

update chandigarh.egbpa_mstr_bpafee_common set "name"='Fee for internal changes during construction', description='Fee for internal changes during construction' where code='OF';
update chandigarh.egbpa_mstr_bpafee_common set "name"='Fee for excess coverage area', description='Fee for excess coverage area' where code='OCF';
update chandigarh.egbpa_mstr_bpafee_common set "name"='Fee for glazing of verandah', description='Fee for glazing of verandah' where code='CCW';
update chandigarh.egbpa_mstr_bpafee_common set "name"='Fee for additional height on second floor of SCFs converted into SCOs', description='Fee for additional height on second floor of SCFs converted into SCOs' where code='CSDC';
update chandigarh.egbpa_mstr_bpafee_common set "name"='Fee for partitions on ground floor on multibays shops', description='Fee for partitions on ground floor on multibays shops' where code='CRC';
update chandigarh.egbpa_mstr_bpafee_common set "name"='Fee for barsati floor height', description='Fee for barsati floor height' where code='CTC';
update chandigarh.egbpa_mstr_bpafee_common set "name"='Fee for stair headway height', description='Fee for stair headway height' where code='CPS';
update chandigarh.egbpa_mstr_bpafee_common set "name"='Fee for water tank location', description='Fee for water tank location' where code='AFWC';

alter table chandigarh.eg_demand_reason_master alter column reasonmaster type character varying(128);

update chandigarh.eg_demand_reason_master set reasonmaster='Fee for internal changes during construction' where code='OF';
update chandigarh.eg_demand_reason_master set reasonmaster='Fee for excess coverage area' where code='OCF';
update chandigarh.eg_demand_reason_master set reasonmaster='Fee for glazing of verandah' where code='CCW';
update chandigarh.eg_demand_reason_master set reasonmaster='Fee for additional height on second floor of SCFs converted into SCOs' where code='CSDC';
update chandigarh.eg_demand_reason_master set reasonmaster='Fee for partitions on ground floor on multibays shops' where code='CRC';
update chandigarh.eg_demand_reason_master set reasonmaster='Fee for barsati floor height' where code='CTC';
update chandigarh.eg_demand_reason_master set reasonmaster='Fee for stair headway height' where code='CPS';
update chandigarh.eg_demand_reason_master set reasonmaster='Fee for water tank location' where code='AFWC';

delete from egbpa_mstr_bpafeemapping where applicationtype='OCCUPANCY_CERTIFICATE' and feesubtype='SANCTION_FEE';

INSERT INTO chandigarh.egbpa_mstr_bpafeemapping (id,applicationtype,feesubtype,servicetype,calculationtype,bpafeecommon,amount,"version",createdby,createddate,lastmodifiedby,lastmodifieddate,applicationsubtype) VALUES 
(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='01'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='ADF'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='01'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='LC'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='01'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='DPF'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='01'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='CCW'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='01'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='CSDC'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='01'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='CRC'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='01'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='CTC'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='01'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='CPS'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='01'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='AFWC'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='01'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='OF'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='01'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='OCF'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='03'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='ADF'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='03'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='LC'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='03'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='DPF'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='03'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='CCW'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='03'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='CSDC'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='03'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='CRC'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='03'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='CTC'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='03'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='CPS'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='03'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='AFWC'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='03'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='OF'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='03'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='OCF'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='04'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='ADF'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='04'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='LC'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='04'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='DPF'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='04'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='CCW'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='04'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='CSDC'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='04'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='CRC'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='04'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='CTC'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='04'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='CPS'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='04'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='AFWC'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='04'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='OF'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='04'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='OCF'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='06'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='ADF'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='06'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='LC'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='06'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='DPF'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='06'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='CCW'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='06'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='CSDC'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='06'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='CRC'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='06'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='CTC'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='06'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='CPS'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='06'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='AFWC'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='06'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='OF'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='06'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='OCF'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='07'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='ADF'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='07'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='LC'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='07'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='DPF'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='07'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='CCW'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='07'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='CSDC'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='07'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='CRC'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='07'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='CTC'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='07'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='CPS'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='07'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='AFWC'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='07'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='OF'),0,0,1,now(),1,now(),NULL)
,(nextval('seq_egbpa_mstr_bpafeemapping'),'OCCUPANCY_CERTIFICATE','SANCTION_FEE',(select id from chandigarh.egbpa_mstr_servicetype where code='07'),'AUTO',(select id from chandigarh.egbpa_mstr_bpafee_common where code='OCF'),0,0,1,now(),1,now(),NULL)
;

delete from chandigarh.eg_wf_matrix where objecttype = 'OccupancyCertificate';

SELECT setval('seq_eg_wf_matrix', (SELECT max(id) FROM chandigarh.eg_wf_matrix));

INSERT INTO chandigarh.eg_wf_matrix (id,department,objecttype,currentstate,currentstatus,pendingactions,currentdesignation,additionalrule,nextstate,nextaction,nextdesignation,nextstatus,validactions,fromqty,toqty,fromdate,todate,"version",enablefields,forwardenabled,smsemailenabled,nextref,rejectenabled) VALUES 
(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','NEW','','Occupancy certificate application creation pending','','Low Risk','Registered','Forwarded to verify application documents','Building Assistant Urban','Registered','Forward',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','Registered','Registered','Forwarded to verify application documents','','Low Risk','Application documents verification in progress','Forwarded to review application documents','Junior Engineer Urban','Document Verification Completed','Forward',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','Application documents verification in progress','Document Verification Completed','Forwarded to review application documents','','Low Risk','Forward to Head Draftsman','Forwarded to Head Draftsman for review','Head Draftsman Urban','Application Reviewed','Forward,Reject',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','Forward to Head Draftsman','Application Reviewed','Forwarded to Head Draftsman for review','','Low Risk','Forward to SDO Building','Forwarded to SDO Building for review','SDO Building Urban','Document Reviewed','Forward',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','Forward to SDO Building','Document Reviewed','Forwarded to SDO Building for review','','Low Risk','AEE Application Approval Pending','Forwarded to E- Assistant Estate Officer for Approval','Assistant Estate Officer','Application Reviewed','Forward,Reject',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','Record Approved',NULL,'Forwarded to generate Occupancy Certificate','','Low Risk','END','END','SDO Building Urban','Order Issued to Applicant','Generate Occupancy Certificate',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','Rejected','','','','Low Risk','generate rejection notice','Application is rejected by approver','SDO Building Urban','Rejected','Generate Rejection Notice',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','LP Initiated','','','','Low Risk','LP Created','Letter To Party Reply Pending','SDO Building Urban','Letter To Party Created','Forward',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','LP Created','','','','Low Risk','LP Reply Received','Forward to LP Initiator pending','SDO Building Urban','Letter To Party Reply Received','Forward',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','Final Approval Process initiated','AEE Approval Completed','Occupancy certificate fee collection pending','','Low Risk','Record Approved','Occupancy certificate fee collection pending','SDO Building Urban','Approved','Approve,Reject',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','Record Approved',NULL,'Occupancy certificate fee collection pending','','Low Risk','Record Approved','Forwarded to generate Occupancy Certificate','SDO Building Urban','Approved','Generate Occupancy Certificate',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','AEE Application Approval Pending','NOC Updated','Forwarded to E- Assistant Estate Officer for Approval','','Low Risk','Final Approval Process initiated','Occupancy certificate fee collection pending','Estate Officer','AEE Approval Completed','Forward,Reject',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
;

INSERT INTO chandigarh.eg_wf_matrix (id,department,objecttype,currentstate,currentstatus,pendingactions,currentdesignation,additionalrule,nextstate,nextaction,nextdesignation,nextstatus,validactions,fromqty,toqty,fromdate,todate,"version",enablefields,forwardenabled,smsemailenabled,nextref,rejectenabled) VALUES 
(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','NEW','','Occupancy certificate application creation pending','','High Risk','Registered','Forwarded to verify application documents','Building Assistant Urban','Registered','Forward',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','Registered','Registered','Forwarded to verify application documents','','High Risk','Application documents verification in progress','Forwarded to review application documents','Junior Engineer Urban','Document Verification Completed','Forward',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','Application documents verification in progress','Document Verification Completed','Forwarded to review application documents','','High Risk','Forward to Head Draftsman','Forwarded to Head Draftsman for review','Head Draftsman Urban','Application Reviewed','Forward,Reject',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','Forward to Head Draftsman','Application Reviewed','Forwarded to Head Draftsman for review','','High Risk','NOC updation in progress','Forwarded to check NOC updation','SDO Building Urban','Document Reviewed','Forward',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','NOC updation in progress','Document Reviewed','Forwarded to check NOC updation','','High Risk','AEE Application Approval Pending','Forwarded to E- Assistant Estate Officer for Approval','Assistant Estate Officer','NOC Updated','Forward,Reject',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','AEE Application Approval Pending','NOC Updated','Forwarded to E- Assistant Estate Officer for Approval','','High Risk','Final Approval Process initiated','Forwarded to generate Occupancy Certificate','Estate Officer','AEE Approval Completed','Forward,Reject',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','Final Approval Process initiated','AEE Approval Completed','Occupancy certificate fee collection pending','','High Risk','Record Approved','Forwarded to generate Occupancy Certificate','SDO Building Urban','Approved','Approve,Reject',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','Record Approved',NULL,'Occupancy certificate fee collection pending','','High Risk','Record Approved','Forwarded to generate Occupancy Certificate','SDO Building Urban','Approved','Generate Occupancy Certificate',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','Record Approved',NULL,'Forwarded to generate Occupancy Certificate','','High Risk','END','END','SDO Building Urban','Order Issued to Applicant','Generate Occupancy Certificate',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','Rejected','','','','High Risk','generate rejection notice','Application is rejected by approver','SDO Building Urban','Rejected','Generate Rejection Notice',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','LP Initiated','','','','High Risk','LP Created','Letter To Party Reply Pending','Building Assistant Urban','Letter To Party Created','Forward',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','LP Created','','','','High Risk','LP Reply Received','Forward to LP Initiator pending','Building Assistant Urban','Letter To Party Reply Received','Forward',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
;

INSERT INTO chandigarh.eg_wf_matrix (id,department,objecttype,currentstate,currentstatus,pendingactions,currentdesignation,additionalrule,nextstate,nextaction,nextdesignation,nextstatus,validactions,fromqty,toqty,fromdate,todate,"version",enablefields,forwardenabled,smsemailenabled,nextref,rejectenabled) VALUES 
(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','NEW','','Occupancy certificate application creation pending','','Medium Risk','Registered','Forwarded to verify application documents','Draftsman','Registered','Forward',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','Registered','Registered','Forwarded to verify application documents','','Medium Risk','Application documents verification in progress','Forwarded to review application documents','Junior Engineer Rural','Document Verification Completed','Forward',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','Application documents verification in progress','Document Verification Completed','Forwarded to review application documents','','Medium Risk','NOC updation in progress','Forwarded to check NOC updation','SDO Building MC','Document Reviewed','Forward',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','NOC updation in progress','Document Reviewed','Forwarded to check NOC updation','','Medium Risk','Final Approval Process initiated','Occupancy certificate fee collection pending','SDO Building MC','NOC Updated','Forward,Reject',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','Final Approval Process initiated','NOC Updated','Occupancy certificate fee collection pending','','Medium Risk','Record Approved','Occupancy certificate fee collection pending','SDO Building MC','Approved','Approve,Reject',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','Record Approved',NULL,'Occupancy certificate fee collection pending','','Medium Risk','Record Approved','Forwarded to generate Occupancy Certificate','SDO Building MC','Approved','Generate Occupancy Certificate',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','Record Approved',NULL,'Forwarded to generate Occupancy Certificate','','Medium Risk','END','END','SDO Building MC','Order Issued to Applicant','Generate Occupancy Certificate',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','Rejected','','','','Medium Risk','generate rejection notice','Application is rejected by approver','SDO Building MC','Rejected','Generate Rejection Notice',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','LP Initiated','','','','Medium Risk','LP Created','Letter To Party Reply Pending','SDO Building MC','Letter To Party Created','Forward',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
,(nextval('seq_eg_wf_matrix'),'ANY','OccupancyCertificate','LP Created','','','','Medium Risk','LP Reply Received','Forward to LP Initiator pending','SDO Building MC','Letter To Party Reply Received','Forward',NULL,NULL,'2019-01-01','2099-04-01',0,NULL,NULL,NULL,NULL,NULL)
;

-----------------------------SBI---------------------
Insert into chandigarh.egcl_servicecategory (id, name, code, isactive, version, createdby, createddate, lastmodifiedby, lastmodifieddate) values
(nextval('seq_egcl_servicecategory'), 'SBI Payment Gateway', 'SBI', true, 0,  (select id from state.eg_user where username='egovernments'), now(), (select id from state.eg_user where username='egovernments'), now());


Insert into chandigarh.egcl_servicedetails (id, name, serviceurl, isenabled, callbackurl, servicetype, code, fund, fundsource, functionary, vouchercreation, scheme, subscheme, servicecategory, isvoucherapproved, vouchercutoffdate, created_by, created_date, modified_by, modified_date, ordernumber) values
(nextval('seq_egcl_servicedetails'), 'SBI Payment Gateway', 'test.sbiepay.sbi/secure/AggregatorHostedListener', true, 'https://obps-test.chandigarhsmartcity.in/collection/citizen/onlineReceipt-acceptMessageFromPaymentGateway.action', 'P', 'SBI', (select id from chandigarh.fund where code='01'), null, null, false, null, null, (select id from chandigarh.egcl_servicecategory where code='SBI'), false, now(), 1, now(), 1, now(), null);

INSERT INTO chandigarh.EGCL_SERVICE_INSTRUMENTACCOUNTS (id,instrumenttype,servicedetails,chartofaccounts,createdby,createddate,lastmodifiedby,lastmodifieddate) VALUES 
(3,(select id from chandigarh.egf_instrumenttype where "type"='online'),(select id from chandigarh.egcl_servicedetails where "name"='SBI Payment Gateway'),(SELECT id FROM chandigarh.chartofaccounts where "name"='Receivables control accounts-Property Taxes'),1,now(),1,now());


-----------------OC -----------------
SELECT setval('seq_egbpa_occupancy', (SELECT max(id) FROM chandigarh.egbpa_occupancy));

INSERT INTO chandigarh.egbpa_occupancy (id,code,"name",isactive,"version",createdby,createddate,lastmodifiedby,lastmodifieddate,maxcoverage,minfar,maxfar,ordernumber,description,colorcode) VALUES 
(nextval('seq_egbpa_occupancy'),'OC','Occupancy Certificate',true,0,1,'2020-03-20 18:26:51.949',1,'2020-03-20 18:26:51.949',65,3,4,1,'occupancy certificate',NULL)
;

SELECT setval('seq_egbpa_sub_occupancy', (SELECT max(id) FROM chandigarh.egbpa_sub_occupancy));

delete from chandigarh.egbpa_usage where suboccupancy = (select id from chandigarh.egbpa_sub_occupancy where colorcode = 3);
delete from chandigarh.egbpa_sub_occupancy where colorcode =3;

INSERT INTO chandigarh.egbpa_sub_occupancy (id,code,"name",ordernumber,isactive,createdby,createddate,lastmodifieddate,lastmodifiedby,"version",description,maxcoverage,minfar,maxfar,occupancy,colorcode,isfeature) VALUES 
(nextval('seq_egbpa_sub_occupancy'),'OC-MIC','Minor Internal Changes',5,true,1,'2020-07-09 21:07:01.601','2020-07-09 21:07:01.601',1,0,'Minor Internal Changes',65,3,4,(select o.id from chandigarh.egbpa_occupancy o where o.code ='OC'),3,true)
;

delete from chandigarh.egbpa_usage where suboccupancy = (select id from chandigarh.egbpa_sub_occupancy where colorcode = 5);
delete from chandigarh.egbpa_sub_occupancy where colorcode =5;

INSERT INTO chandigarh.egbpa_sub_occupancy (id,code,"name",ordernumber,isactive,createdby,createddate,lastmodifieddate,lastmodifiedby,"version",description,maxcoverage,minfar,maxfar,occupancy,colorcode,isfeature) VALUES 
(nextval('seq_egbpa_sub_occupancy'),'OC-GOV','Glazing Of Verandah',5,true,1,'2020-07-09 21:07:01.601','2020-07-09 21:07:01.601',1,0,'Glazing Of Verandah',65,3,4,(select o.id from chandigarh.egbpa_occupancy o where o.code ='OC'),5,true)
;